# CLUB URL DICTIONARY (Expand this to all 92)
CLUBS = {
    'Arsenal': 'https://www.facebook.com/Arsenal',
    'Aston Villa': 'https://www.facebook.com/avfcofficial',
    'AFC Bournemouth': 'https://www.facebook.com/afcb/',
    'Brentford': 'https://www.facebook.com/brentfordfootballclub1889/',
    'Brighton & Hove Albion': 'https://www.facebook.com/OfficialBHAFC',
    'Chelsea': 'https://www.facebook.com/ChelseaFC',
    'Crystal Palace': 'https://www.facebook.com/officialcpfc',
    'Everton': 'https://www.facebook.com/Everton',
    'Fulham': 'https://www.facebook.com/FulhamFC',
    'Ipswich Town': 'https://www.facebook.com/OfficialITFC',
    'Leicester City': 'https://www.facebook.com/LCFC',
    'Liverpool': 'https://www.facebook.com/LiverpoolFC',
    'Manchester City': 'https://www.facebook.com/mancity',
    'Manchester United': 'https://www.facebook.com/manchesterunited',
    'Newcastle United': 'https://www.facebook.com/newcastleunited',
    'Nottingham Forest': 'https://www.facebook.com/officialnffc/',
    'Southampton': 'https://www.facebook.com/SouthamptonFC',
    'Tottenham Hotspur': 'https://www.facebook.com/TottenhamHotspur',
    'West Ham United': 'https://www.facebook.com/WestHam/',
    'Wolverhampton Wanderers': 'https://www.facebook.com/Wolves',
        
    'Blackburn Rovers': 'https://www.facebook.com/1Rovers/',
    'Bristol City': 'https://www.facebook.com/BristolCityFC',
    'Burnley': 'https://www.facebook.com/burnleyofficial/',
    'Cardiff City': 'https://www.facebook.com/CardiffCityFC',
    'Coventry City': 'https://www.facebook.com/coventrycityfc',
    'Derby County': 'https://www.facebook.com/dcfcofficial/',
    'Hull City': 'https://www.facebook.com/hullcity',
    'Leeds United': 'https://www.facebook.com/LeedsUnited',
    'Luton Town': 'https://www.facebook.com/LutonTown/',
    'Middlesbrough': 'https://www.facebook.com/MFCofficial/',
    'Millwall': 'https://www.facebook.com/MillwallFCOfficial/',
    'Norwich City': 'https://www.facebook.com/NorwichCityFootballClub/',
    'Oxford United': 'https://www.facebook.com/OUFCOfficial',
    'Plymouth Argyle': 'https://www.facebook.com/Argyle/',
    'Portsmouth': 'https://www.facebook.com/officialpfc/',
    'Preston North End': 'https://www.facebook.com/officialpnefc',
    'Queens Park Rangers': 'https://www.facebook.com/OfficialQPRFC/',
    'Sheffield United': 'https://www.facebook.com/sheffieldunited',
    'Sheffield Wednesday': 'https://www.facebook.com/sheffieldwednesday',
    'Stoke City': 'https://www.facebook.com/stokecity',
    'Sunderland': 'https://www.facebook.com/SunderlandAFC',
    'Swansea City': 'https://www.facebook.com/SwanseaCityFC',
    'Watford': 'https://www.facebook.com/watfordfc',
    'West Bromwich Albion': 'https://www.facebook.com/westbromwichalbionofficial/',

    'Barnsley': 'https://www.facebook.com/BarnsleyFC/',
    'Birmingham City': 'https://www.facebook.com/BCFCofficial',
    'Blackpool': 'https://www.facebook.com/officialblackpoolfc',
    'Bolton Wanderers': 'https://www.facebook.com/officialbwfc',
    'Bristol Rovers': 'https://www.facebook.com/OfficialBristolRovers',
    'Burton Albion': 'https://www.facebook.com/burtonalbionfc',
    'Cambridge United': 'https://www.facebook.com/OfficialCambridgeUnited/',
    'Charlton Athletic': 'https://www.facebook.com/OfficialCAFC/',
    'Crawley Town': 'https://www.facebook.com/crawleytown/',
    'Exeter City': 'https://www.facebook.com/exetercityfc',
    'Huddersfield Town': 'https://www.facebook.com/htafc/',
    'Leyton Orient': 'https://www.facebook.com/lofcofficial',
    'Lincoln City': 'https://www.facebook.com/lincolncityfc',
    'Mansfield Town': 'https://www.facebook.com/mansfieldtownfootballclub',
    'Northampton Town': 'https://www.facebook.com/northamptontownfc',
    'Peterborough United': 'https://www.facebook.com/theposh/',
    'Reading': 'https://www.facebook.com/ReadingFC',
    'Rotherham United': 'https://www.facebook.com/rotherhamunited',
    'Shrewsbury Town': 'https://www.facebook.com/shrewsburytown',
    'Stevenage': 'https://www.facebook.com/StevenageFCOfficial/',
    'Stockport County': 'https://www.facebook.com/stockportcounty/',
    'Wigan Athletic': 'https://www.facebook.com/wiganathletic',
    'Wrexham': 'https://www.facebook.com/wrexhamfootballclub/',
    'Wycombe Wanderers': 'https://www.facebook.com/wwfcofficial',

    'Accrington Stanley': 'https://www.facebook.com/ASFCofficial',
    'AFC Wimbledon': 'https://www.facebook.com/afcwimbledon',
    'Barrow': 'https://www.facebook.com/barrowofficial/',
    'Bradford City': 'https://www.facebook.com/officialbantams',
    'Bromley': 'https://www.facebook.com/BromleyFC/',
    'Carlisle United': 'https://www.facebook.com/carlisleunitedfc',
    'Cheltenham Town': 'https://www.facebook.com/CTFCofficial',
    'Chesterfield': 'https://www.facebook.com/ChesterfieldFC',
    'Colchester United': 'https://www.facebook.com/colchesterunitedfc',
    'Crawley Town': 'https://www.facebook.com/crawleytown',
    'Crewe Alexandra': 'https://www.facebook.com/crewealexofficial',
    'Doncaster Rovers': 'https://www.facebook.com/DoncasterRoversFC',
    'Fleetwood Town': 'https://www.facebook.com/FleetwoodTownFC',
    'Gillingham': 'https://www.facebook.com/GillinghamFootballClubOfficial',
    'Grimsby Town': 'https://www.facebook.com/officialgtfc',
    'Harrogate Town': 'https://www.facebook.com/HarrogateTownAFC/',
    'Milton Keynes Dons': 'https://www.facebook.com/mkdonsfc',
    'Morecambe': 'https://www.facebook.com/morecambefootballclub',
    'Newport County': 'https://www.facebook.com/newportcountyafc',
    'Notts County': 'https://www.facebook.com/NottsCountyFootballClub',
    'Port Vale': 'https://www.facebook.com/OfficialPVFC/',
    'Salford City': 'https://www.facebook.com/salfordcityfc',
    'Swindon Town': 'https://www.facebook.com/SwindonTownFootballClub',
    'Tranmere Rovers': 'https://www.facebook.com/trfcofficial/',
    'Walsall': 'https://www.facebook.com/OfficialWalsallFC',
    'Barnet': 'https://www.facebook.com/BarnetFootballClub',
    'Oldham Athletic': 'https://www.facebook.com/OfficialOAFC'
}